version: '3.8'

# 프로덕션 환경용 Docker Compose 오버라이드
services:
  hananavilite:
    environment:
      - LOG_LEVEL=WARNING
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    restart: always
    
  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: hananavilite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./ui/dist:/usr/share/nginx/html
    depends_on:
      - hananavilite
    restart: always
    networks:
      - hananavilite-network
    profiles:
      - nginx

  redis:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  ollama:
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always