
services:
  # HanaNaviLite 메인 애플리케이션
  hananavilite:
    build: .
    container_name: hananavilite-app
    ports:
      - "8011:8011"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - OLLAMA_BASE_URL=http://host-gateway:11434  # 로컬 Ollama 사용 (권장) - 현재 11435 포트
      # - OLLAMA_BASE_URL=http://ollama:11434  # Ollama 컨테이너 사용시 (docker-compose --profile ollama-container up -d)
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - LLM_MODEL=gemma3:12b-it-qat
      - DATABASE_URL=sqlite:///data/hananavilite.db
      - LOG_LEVEL=INFO
      - NVIDIA_VISIBLE_DEVICES=all
      - API_PORT=8011
    extra_hosts:
      - "host-gateway:host-gateway"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - hananavilite-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Redis 캐시 서버 (선택적)
  redis:
    image: redis:7-alpine
    container_name: hananavilite-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - hananavilite-network

  # Ollama 서버 (선택적 - 로컬 Ollama 대신 사용 가능)
  # 사용법: docker-compose --profile ollama-container up -d
  # 주의: 현재는 로컬 Ollama(11435)를 사용하므로 이 컨테이너는 기본적으로 실행되지 않음
  ollama:
    image: ollama/ollama:latest
    container_name: hananavilite-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - hananavilite-network
    profiles:
      - ollama-container  # 이 프로파일로 선택적 실행

volumes:
  redis_data:
  ollama_data:
  huggingface_cache:

networks:
  hananavilite-network:
    driver: bridge